// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

type APIKey struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type APIKeyConnection struct {
	Edges []*APIKeyEdge `json:"edges"`
}

type APIKeyEdge struct {
	Node *APIKey `json:"node"`
}

type Artifact struct {
	ID              string            `json:"id"`
	State           *string           `json:"state,omitempty"`
	CurrentManifest *ArtifactManifest `json:"currentManifest,omitempty"`
}

type ArtifactAliasInput struct {
	ArtifactCollectionName string `json:"artifactCollectionName"`
	Alias                  string `json:"alias"`
}

type ArtifactManifest struct {
	ID   string    `json:"id"`
	File *FileNode `json:"file,omitempty"`
}

type CommitArtifactInput struct {
	ArtifactID string  `json:"artifactID"`
	Digest     *string `json:"digest,omitempty"`
}

type CommitArtifactPayload struct {
	Artifact *Artifact `json:"artifact,omitempty"`
}

type CreateArtifactFileInput struct {
	Name               string  `json:"name"`
	Md5                *string `json:"md5,omitempty"`
	ArtifactManifestID *string `json:"artifactManifestID,omitempty"`
}

type CreateArtifactFilesInput struct {
	ArtifactID         string                     `json:"artifactID"`
	ArtifactManifestID string                     `json:"artifactManifestID"`
	EntityName         string                     `json:"entityName"`
	ProjectName        *string                    `json:"projectName,omitempty"`
	RunName            string                     `json:"runName"`
	Files              []*CreateArtifactFileInput `json:"files"`
}

type CreateArtifactFilesPayload struct {
	Files *FileConnection `json:"files,omitempty"`
}

type CreateArtifactInput struct {
	EntityName             string                `json:"entityName"`
	ProjectName            *string               `json:"projectName,omitempty"`
	RunName                string                `json:"runName"`
	ArtifactTypeName       string                `json:"artifactTypeName"`
	ArtifactCollectionName string                `json:"artifactCollectionName"`
	Digest                 *string               `json:"digest,omitempty"`
	Description            *string               `json:"description,omitempty"`
	Metadata               *string               `json:"metadata,omitempty"`
	Aliases                []*ArtifactAliasInput `json:"aliases,omitempty"`
	ClientID               *string               `json:"clientID,omitempty"`
}

type CreateArtifactManifestInput struct {
	ArtifactID     string  `json:"artifactID"`
	BaseArtifactID *string `json:"baseArtifactID,omitempty"`
	EntityName     string  `json:"entityName"`
	ProjectName    *string `json:"projectName,omitempty"`
	RunName        string  `json:"runName"`
	Name           string  `json:"name"`
	Digest         string  `json:"digest"`
	Type           *int    `json:"type,omitempty"`
}

type CreateArtifactManifestPayload struct {
	ArtifactManifest *ArtifactManifest `json:"artifactManifest,omitempty"`
}

type CreateArtifactPayload struct {
	Artifact *Artifact `json:"artifact,omitempty"`
}

type CreateRunFilesInput struct {
	RunName     string   `json:"runName"`
	EntityName  string   `json:"entityName"`
	ProjectName *string  `json:"projectName,omitempty"`
	Files       []string `json:"files"`
}

type CreateRunFilesPayload struct {
	RunID         *string           `json:"runID,omitempty"`
	Files         []*FileUploadInfo `json:"files,omitempty"`
	UploadHeaders []string          `json:"uploadHeaders,omitempty"`
}

type Entity struct {
	ID           string        `json:"id"`
	Name         string        `json:"name"`
	Organization *Organization `json:"organization,omitempty"`
}

type Feature struct {
	Name      string `json:"name"`
	IsEnabled bool   `json:"isEnabled"`
}

type FileConnection struct {
	Edges []*FileEdge `json:"edges"`
}

type FileEdge struct {
	Node *FileUploadInfo `json:"node"`
}

type FileNode struct {
	ID        string  `json:"id"`
	DirectURL *string `json:"directUrl,omitempty"`
}

type FileUploadInfo struct {
	ID            string   `json:"id"`
	Name          string   `json:"name"`
	UploadURL     *string  `json:"uploadUrl,omitempty"`
	UploadHeaders []string `json:"uploadHeaders"`
}

type Mutation struct {
}

type Organization struct {
	ID                      string  `json:"id"`
	Name                    string  `json:"name"`
	CoreWeaveOrganizationID *string `json:"coreWeaveOrganizationId,omitempty"`
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type Project struct {
	ID         string         `json:"id"`
	InternalID *string        `json:"internalId,omitempty"`
	Name       string         `json:"name"`
	Entity     *Entity        `json:"entity"`
	ReadOnly   *bool          `json:"readOnly,omitempty"`
	RunCount   *int           `json:"runCount,omitempty"`
	Runs       *RunConnection `json:"runs,omitempty"`
	Run        *Run           `json:"run,omitempty"`
	Bucket     *Run           `json:"bucket,omitempty"`
}

type Query struct {
}

type Run struct {
	ID               string   `json:"id"`
	Name             string   `json:"name"`
	DisplayName      *string  `json:"displayName,omitempty"`
	Project          *Project `json:"project,omitempty"`
	Config           *string  `json:"config,omitempty"`
	SummaryMetrics   *string  `json:"summaryMetrics,omitempty"`
	State            *string  `json:"state,omitempty"`
	Host             *string  `json:"host,omitempty"`
	Program          *string  `json:"program,omitempty"`
	Commit           *string  `json:"commit,omitempty"`
	Tags             []string `json:"tags,omitempty"`
	Description      *string  `json:"description,omitempty"`
	Notes            *string  `json:"notes,omitempty"`
	Group            *string  `json:"group,omitempty"`
	JobType          *string  `json:"jobType,omitempty"`
	SweepName        *string  `json:"sweepName,omitempty"`
	HistoryLineCount *int     `json:"historyLineCount,omitempty"`
	EventsLineCount  *int     `json:"eventsLineCount,omitempty"`
	LogLineCount     *int     `json:"logLineCount,omitempty"`
	CreatedAt        *string  `json:"createdAt,omitempty"`
	UpdatedAt        *string  `json:"updatedAt,omitempty"`
	HeartbeatAt      *string  `json:"heartbeatAt,omitempty"`
	HistoryTail      *string  `json:"historyTail,omitempty"`
	EventsTail       *string  `json:"eventsTail,omitempty"`
	ReadOnly         *bool    `json:"readOnly,omitempty"`
	Stopped          *bool    `json:"stopped,omitempty"`
	SystemMetrics    *string  `json:"systemMetrics,omitempty"`
	HistoryKeys      *string  `json:"historyKeys,omitempty"`
	User             *RunUser `json:"user,omitempty"`
	WandbConfig      *string  `json:"wandbConfig,omitempty"`
}

type RunConnection struct {
	Edges    []*RunEdge `json:"edges"`
	PageInfo *PageInfo  `json:"pageInfo"`
}

type RunEdge struct {
	Node   *Run   `json:"node"`
	Cursor string `json:"cursor"`
}

type RunUser struct {
	Name     *string `json:"name,omitempty"`
	Username *string `json:"username,omitempty"`
}

type ServerInfo struct {
	CliVersionInfo         *string      `json:"cliVersionInfo,omitempty"`
	LatestLocalVersionInfo *VersionInfo `json:"latestLocalVersionInfo,omitempty"`
	ServerVersion          *string      `json:"serverVersion,omitempty"`
	Features               []*Feature   `json:"features,omitempty"`
}

type Team struct {
	Name string `json:"name"`
}

type TeamConnection struct {
	Edges []*TeamEdge `json:"edges"`
}

type TeamEdge struct {
	Node *Team `json:"node"`
}

type UpsertBucketInput struct {
	ID             *string  `json:"id,omitempty"`
	Name           *string  `json:"name,omitempty"`
	Entity         *string  `json:"entity,omitempty"`
	EntityName     *string  `json:"entityName,omitempty"`
	Project        *string  `json:"project,omitempty"`
	ModelName      *string  `json:"modelName,omitempty"`
	Config         *string  `json:"config,omitempty"`
	Summary        *string  `json:"summary,omitempty"`
	SummaryMetrics *string  `json:"summaryMetrics,omitempty"`
	State          *string  `json:"state,omitempty"`
	Host           *string  `json:"host,omitempty"`
	Program        *string  `json:"program,omitempty"`
	Commit         *string  `json:"commit,omitempty"`
	Tags           []string `json:"tags,omitempty"`
	DisplayName    *string  `json:"displayName,omitempty"`
	Notes          *string  `json:"notes,omitempty"`
	GroupName      *string  `json:"groupName,omitempty"`
	JobType        *string  `json:"jobType,omitempty"`
	SweepName      *string  `json:"sweepName,omitempty"`
	Sweep          *string  `json:"sweep,omitempty"`
	Description    *string  `json:"description,omitempty"`
	Debug          *bool    `json:"debug,omitempty"`
	JobProgram     *string  `json:"jobProgram,omitempty"`
	JobRepo        *string  `json:"jobRepo,omitempty"`
}

type UpsertBucketPayload struct {
	Bucket   *Run  `json:"bucket,omitempty"`
	Inserted *bool `json:"inserted,omitempty"`
}

type User struct {
	ID        string            `json:"id"`
	Name      *string           `json:"name,omitempty"`
	Username  string            `json:"username"`
	Email     string            `json:"email"`
	Entity    string            `json:"entity"`
	Admin     *bool             `json:"admin,omitempty"`
	DeletedAt *string           `json:"deletedAt,omitempty"`
	Flags     *string           `json:"flags,omitempty"`
	Teams     *TeamConnection   `json:"teams,omitempty"`
	APIKeys   *APIKeyConnection `json:"apiKeys,omitempty"`
}

type VersionInfo struct {
	LatestVersionString         *string `json:"latestVersionString,omitempty"`
	VersionOnThisInstanceString *string `json:"versionOnThisInstanceString,omitempty"`
	OutOfDate                   *bool   `json:"outOfDate,omitempty"`
}
