package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.86

import (
	"context"
	"database/sql"
	"encoding/json"
	"fmt"

	"github.com/google/uuid"
	"github.com/sarna/worb/internal/auth"
	"github.com/sarna/worb/internal/store"
)

// UpsertBucket is the resolver for the upsertBucket field.
func (r *mutationResolver) UpsertBucket(ctx context.Context, input *UpsertBucketInput, id *string, name *string, entity *string, project *string, config *string, summary *string, state *string, host *string, program *string, commit *string, tags []string, displayName *string, notes *string, groupName *string, jobType *string, sweepName *string, description *string) (*UpsertBucketPayload, error) {
	if input != nil {
		if input.ID != nil && id == nil {
			id = input.ID
		}
		if input.Name != nil && name == nil {
			name = input.Name
		}
		if input.Entity != nil && entity == nil {
			entity = input.Entity
		}
		if input.EntityName != nil && entity == nil {
			entity = input.EntityName
		}
		if input.Project != nil && project == nil {
			project = input.Project
		}
		if input.ModelName != nil && project == nil {
			project = input.ModelName
		}
		if input.Config != nil && config == nil {
			config = input.Config
		}
		if input.Summary != nil && summary == nil {
			summary = input.Summary
		}
		if input.SummaryMetrics != nil && summary == nil {
			summary = input.SummaryMetrics
		}
		if input.State != nil && state == nil {
			state = input.State
		}
		if input.Host != nil && host == nil {
			host = input.Host
		}
		if input.Program != nil && program == nil {
			program = input.Program
		}
		if input.Commit != nil && commit == nil {
			commit = input.Commit
		}
		if input.Tags != nil && tags == nil {
			tags = input.Tags
		}
		if input.DisplayName != nil && displayName == nil {
			displayName = input.DisplayName
		}
		if input.Notes != nil && notes == nil {
			notes = input.Notes
		}
		if input.GroupName != nil && groupName == nil {
			groupName = input.GroupName
		}
		if input.JobType != nil && jobType == nil {
			jobType = input.JobType
		}
		if input.SweepName != nil && sweepName == nil {
			sweepName = input.SweepName
		}
		if input.Sweep != nil && sweepName == nil {
			sweepName = input.Sweep
		}
	}

	params := store.UpsertRunParams{}

	if id != nil {
		params.ID = *id
	}
	if name != nil {
		params.Name = *name
	}
	if entity != nil {
		params.Entity = *entity
	} else {
		params.Entity = "local"
	}
	if project != nil {
		params.Project = *project
	} else {
		params.Project = "default"
	}
	if config != nil {
		params.Config = json.RawMessage(*config)
	}
	if summary != nil {
		params.Summary = json.RawMessage(*summary)
	}
	if state != nil {
		params.State = *state
	}
	if host != nil {
		params.Host = *host
	}
	if program != nil {
		params.Program = *program
	}
	if commit != nil {
		params.GitCommit = *commit
	}
	if displayName != nil {
		params.DisplayName = *displayName
	}
	if notes != nil {
		params.Notes = *notes
	}
	if groupName != nil {
		params.GroupName = *groupName
	}
	if jobType != nil {
		params.JobType = *jobType
	}
	if sweepName != nil {
		params.SweepName = *sweepName
	}
	if tags != nil {
		tagsJSON, _ := json.Marshal(tags)
		params.Tags = tagsJSON
	}

	run, err := r.Store.UpsertRun(params)
	if err != nil {
		return nil, fmt.Errorf("upsert run: %w", err)
	}

	gqlRun := storeRunToGQL(run)
	proj, _ := r.Store.GetProject(run.ProjectID)
	if proj != nil {
		gqlRun.Project = &Project{
			ID:   proj.ID,
			Name: proj.Name,
			Entity: &Entity{
				ID:           proj.Entity,
				Name:         proj.Entity,
				Organization: &Organization{ID: proj.Entity, Name: proj.Entity},
			},
		}
	}

	inserted := true
	return &UpsertBucketPayload{
		Bucket:   gqlRun,
		Inserted: &inserted,
	}, nil
}

// CreateArtifact is the resolver for the createArtifact field.
func (r *mutationResolver) CreateArtifact(ctx context.Context, input CreateArtifactInput) (*CreateArtifactPayload, error) {
	projectName := "default"
	if input.ProjectName != nil {
		projectName = *input.ProjectName
	}
	proj, err := r.Store.EnsureProject(input.EntityName, projectName)
	if err != nil {
		return nil, err
	}

	run, err := r.Store.GetRunByName(proj.ID, input.RunName)
	if err != nil {
		return nil, fmt.Errorf("find run: %w", err)
	}

	var metadata json.RawMessage
	if input.Metadata != nil {
		metadata = json.RawMessage(*input.Metadata)
	}

	artifact, err := r.Store.CreateArtifact(run.ID, input.ArtifactTypeName, input.ArtifactCollectionName, metadata)
	if err != nil {
		return nil, err
	}

	state := artifact.State
	return &CreateArtifactPayload{
		Artifact: &Artifact{
			ID:    artifact.ID,
			State: &state,
		},
	}, nil
}

// CommitArtifact is the resolver for the commitArtifact field.
func (r *mutationResolver) CommitArtifact(ctx context.Context, input CommitArtifactInput) (*CommitArtifactPayload, error) {
	digest := ""
	if input.Digest != nil {
		digest = *input.Digest
	}
	if err := r.Store.CommitArtifact(input.ArtifactID, digest); err != nil {
		return nil, err
	}

	state := "committed"
	return &CommitArtifactPayload{
		Artifact: &Artifact{
			ID:    input.ArtifactID,
			State: &state,
		},
	}, nil
}

// CreateArtifactManifest is the resolver for the createArtifactManifest field.
func (r *mutationResolver) CreateArtifactManifest(ctx context.Context, input CreateArtifactManifestInput) (*CreateArtifactManifestPayload, error) {
	manifestID := uuid.New().String()
	fileID := uuid.New().String()
	uploadURL := fmt.Sprintf("%s/files/upload/%s", GetBaseURL(ctx), fileID)

	return &CreateArtifactManifestPayload{
		ArtifactManifest: &ArtifactManifest{
			ID: manifestID,
			File: &FileNode{
				ID:        fileID,
				DirectURL: &uploadURL,
			},
		},
	}, nil
}

// CreateArtifactFiles is the resolver for the createArtifactFiles field.
func (r *mutationResolver) CreateArtifactFiles(ctx context.Context, input CreateArtifactFilesInput) (*CreateArtifactFilesPayload, error) {
	var edges []*FileEdge
	for _, f := range input.Files {
		fileID := uuid.New().String()
		uploadURL := fmt.Sprintf("%s/files/upload/%s", GetBaseURL(ctx), fileID)
		edges = append(edges, &FileEdge{
			Node: &FileUploadInfo{
				ID:            fileID,
				Name:          f.Name,
				UploadURL:     &uploadURL,
				UploadHeaders: []string{},
			},
		})
	}

	return &CreateArtifactFilesPayload{
		Files: &FileConnection{Edges: edges},
	}, nil
}

// CreateRunFiles is the resolver for the createRunFiles field.
func (r *mutationResolver) CreateRunFiles(ctx context.Context, input CreateRunFilesInput) (*CreateRunFilesPayload, error) {
	projectName := "default"
	if input.ProjectName != nil {
		projectName = *input.ProjectName
	}
	proj, err := r.Store.EnsureProject(input.EntityName, projectName)
	if err != nil {
		return nil, err
	}

	run, err := r.Store.GetRunByName(proj.ID, input.RunName)
	if err != nil {
		return nil, fmt.Errorf("find run: %w", err)
	}

	var files []*FileUploadInfo
	for _, fname := range input.Files {
		fileID := uuid.New().String()
		uploadURL := fmt.Sprintf("%s/files/upload/%s", GetBaseURL(ctx), fileID)
		files = append(files, &FileUploadInfo{
			ID:            fileID,
			Name:          fname,
			UploadURL:     &uploadURL,
			UploadHeaders: []string{},
		})
	}

	return &CreateRunFilesPayload{
		RunID:         &run.ID,
		Files:         files,
		UploadHeaders: []string{},
	}, nil
}

// RunCount is the resolver for the runCount field.
func (r *projectResolver) RunCount(ctx context.Context, obj *Project, filters *string) (*int, error) {
	var displayName string
	if filters != nil {
		var f map[string]interface{}
		if err := json.Unmarshal([]byte(*filters), &f); err == nil {
			if dn, ok := f["display_name"].(string); ok {
				displayName = dn
			}
		}
	}

	runs, err := r.Store.ListRunsFiltered(obj.ID, displayName)
	if err != nil && err != sql.ErrNoRows {
		return nil, err
	}
	count := len(runs)
	return &count, nil
}

// Runs is the resolver for the runs field.
func (r *projectResolver) Runs(ctx context.Context, obj *Project, first *int, order *string, filters *string, after *string) (*RunConnection, error) {
	var displayName string
	if filters != nil {
		var f map[string]interface{}
		if err := json.Unmarshal([]byte(*filters), &f); err == nil {
			if dn, ok := f["display_name"].(string); ok {
				displayName = dn
			}
		}
	}

	runs, err := r.Store.ListRunsFiltered(obj.ID, displayName)
	if err != nil && err != sql.ErrNoRows {
		return nil, err
	}

	var edges []*RunEdge
	for _, run := range runs {
		edges = append(edges, &RunEdge{
			Node:   storeRunToGQL(run),
			Cursor: run.ID,
		})
	}

	if first != nil && len(edges) > *first {
		edges = edges[:*first]
	}

	return &RunConnection{
		Edges:    edges,
		PageInfo: &PageInfo{HasNextPage: false},
	}, nil
}

// Run is the resolver for the run field.
func (r *projectResolver) Run(ctx context.Context, obj *Project, name string) (*Run, error) {
	run, err := r.Store.GetRunByName(obj.ID, name)
	if err != nil {
		return nil, nil
	}
	return storeRunToGQL(run), nil
}

// Bucket is the resolver for the bucket field.
func (r *projectResolver) Bucket(ctx context.Context, obj *Project, name string, missingOk *bool) (*Run, error) {
	run, err := r.Store.GetRunByName(obj.ID, name)
	if err != nil {
		if missingOk != nil && *missingOk {
			return nil, nil
		}
		return nil, err
	}
	return storeRunToGQL(run), nil
}

// Viewer is the resolver for the viewer field.
func (r *queryResolver) Viewer(ctx context.Context) (*User, error) {
	entity := auth.EntityFromContext(ctx)
	flags := "{}"
	return &User{
		ID:       entity + "-user",
		Username: entity,
		Email:    entity + "@worb.cloud",
		Entity:   entity,
		Flags:    &flags,
		Teams: &TeamConnection{
			Edges: []*TeamEdge{},
		},
	}, nil
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, name *string, entityName *string) (*Project, error) {
	projectName := "default"
	if name != nil {
		projectName = *name
	}
	entity := "local"
	if entityName != nil {
		entity = *entityName
	}

	proj, err := r.Store.EnsureProject(entity, projectName)
	if err != nil {
		return nil, err
	}

	return &Project{
		ID:   proj.ID,
		Name: proj.Name,
		Entity: &Entity{
			ID:           entity,
			Name:         entity,
			Organization: &Organization{ID: entity, Name: entity},
		},
	}, nil
}

// Model is the resolver for the model field.
func (r *queryResolver) Model(ctx context.Context, name *string, entityName *string) (*Project, error) {
	projectName := "default"
	if name != nil {
		projectName = *name
	}
	entity := "local"
	if entityName != nil {
		entity = *entityName
	}

	proj, err := r.Store.EnsureProject(entity, projectName)
	if err != nil {
		return nil, err
	}

	return &Project{
		ID:   proj.ID,
		Name: proj.Name,
		Entity: &Entity{
			ID:           entity,
			Name:         entity,
			Organization: &Organization{ID: entity, Name: entity},
		},
	}, nil
}

// Entity is the resolver for the entity field.
func (r *queryResolver) Entity(ctx context.Context, name *string) (*Entity, error) {
	n := "local"
	if name != nil {
		n = *name
	}
	return &Entity{ID: n, Name: n, Organization: &Organization{ID: n, Name: n}}, nil
}

// ServerInfo is the resolver for the serverInfo field.
func (r *queryResolver) ServerInfo(ctx context.Context) (*ServerInfo, error) {
	version := "0.1.0"
	outOfDate := false
	return &ServerInfo{
		ServerVersion: &version,
		LatestLocalVersionInfo: &VersionInfo{
			LatestVersionString:         &version,
			VersionOnThisInstanceString: &version,
			OutOfDate:                   &outOfDate,
		},
		Features: []*Feature{},
	}, nil
}

// WandbConfig is the resolver for the wandbConfig field.
func (r *runResolver) WandbConfig(ctx context.Context, obj *Run, keys []string) (*string, error) {
	if obj.Config == nil {
		empty := "{}"
		return &empty, nil
	}

	var config map[string]json.RawMessage
	if err := json.Unmarshal([]byte(*obj.Config), &config); err != nil {
		empty := "{}"
		return &empty, nil
	}

	wandbRaw, ok := config["_wandb"]
	if !ok {
		empty := "{}"
		return &empty, nil
	}

	var wandbWrapper struct {
		Value map[string]json.RawMessage `json:"value"`
	}
	if err := json.Unmarshal(wandbRaw, &wandbWrapper); err != nil {
		empty := "{}"
		return &empty, nil
	}

	if len(keys) == 0 {
		result, _ := json.Marshal(wandbWrapper.Value)
		s := string(result)
		return &s, nil
	}

	filtered := make(map[string]json.RawMessage)
	for _, k := range keys {
		if v, exists := wandbWrapper.Value[k]; exists {
			filtered[k] = v
		}
	}
	result, _ := json.Marshal(filtered)
	s := string(result)
	return &s, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Project returns ProjectResolver implementation.
func (r *Resolver) Project() ProjectResolver { return &projectResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Run returns RunResolver implementation.
func (r *Resolver) Run() RunResolver { return &runResolver{r} }

type mutationResolver struct{ *Resolver }
type projectResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type runResolver struct{ *Resolver }
